version = 1
SPDX-PackageName = "Slang Binaries"
SPDX-PackageSupplier = "The Khronos Group, Inc."
SPDX-PackageDownloadLocation = "https://github.com/shader-slang/slang-binaries"

[[annotations]]
path = "spirv-tools/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Khronos Group, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".github/**", ".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "certificate/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "LicenseRef-CA-Bundle-NOASSERTION"
SPDX-License-Identifier = "LicenseRef-CA-Bundle-NOASSERTION"

[[annotations]]
path = "bin/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Microsoft"
SPDX-License-Identifier = "LicenseRef-Microsoft-DirectX"

[[annotations]]
path = [
    "bin/windows-aarch64/*",
    "bin/windows-x64/dxcompiler.dll",
    "bin/windows-x64/dxil.dll",
    "bin/windows-x86/dxcompiler.dll",
    "bin/windows-x86/dxil.dll"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Microsoft"
SPDX-License-Identifier = "LLVM-exception"

[[annotations]]
path = [
    "bin/windows-x64/d3dcompiler_47.dll",
    "bin/windows-x86/d3dcompiler_47.dll",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Microsoft"
SPDX-License-Identifier = "LicenseRef-Microsoft-Windows-SDK"

[[annotations]]
path = ["CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Khronos Group, Inc."
SPDX-License-Identifier = "CC-BY-4.0"
